[package]
name = "ta-ko-ho/random-repo-for-testing"
version = "0.1.1"
description = "wasmer-tests/wasmer-edge-svelte-sample website"
repository = "https://github.com/ta-ko-ho/random-repo-for-testing"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "build"
